---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart-name: {{ .Chart.Name }}
    release-name: {{ .Release.Name }}
data:
  dessert: {{ .Values.dessert }}