apiVersion: v2
name: helm-debugging
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mysubchart1
    repository: "file://charts/mysubchart1"
    version: 0.1.0
    # A
    #condition: deployments.mysubchart1.enabled
    # B
    condition: mysubchart1.enabled
  - name: mysubchart2
    repository: "file://charts/mysubchart2"
    version: 0.1.0
    # A
    #condition: deployments.mysubchart2.enabled
    # B
    condition: mysubchart2.enabled